services:
  mailpit:
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-mailpit
    image: axllent/mailpit:v${MAILPIT_VERSION:-1.22.3}
    ports:
      - ${MAILPIT_WEB_PORT:-8025}:8025
      - ${MAILPIT_SMTP_PORT:-1025}:1025
    restart: unless-stopped
    volumes:
      - mailpitdata:/data

  memcached:
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-memcached
    image: memcached:${MEMCACHED_VERSION:-1.6-alpine}

  mysql:
    command: [
      '--character-set-server=${MYSQL_ENCODING:-utf8mb4}',
      '--collation-server=${MYSQL_COLLATION:-utf8mb4_unicode_ci}'
    ]
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-docker}
      - MYSQL_USER=${MYSQL_USER:-docker}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    image: mysql:${MYSQL_VERSION:-8.4}
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - mysqldata:/var/lib/mysql

  nginx:
    build:
      args:
        - NGINX_VERSION
        - SITE_URL
        - SITE_TYPE
      context: ./docker/nginx
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-nginx
    depends_on:
      - php
    ports:
      - ${NGINX_PORT_UNSECURE:-80}:80
      - ${NGINX_PORT_SECURE:-443}:443
    volumes:
      - ./www:/srv/www
      - ./logs/nginx:/var/log/nginx
    working_dir: /srv/www

  nodejs:
    build:
      args:
        - NODEJS_VERSION
        - USER_ID
        - GROUP_ID
      context: ./docker/nodejs
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-nodejs
    environment:
      - NPM_CONFIG_CACHE=/.config/npm
    image: node:${NODEJS_VERSION:-22.14-alpine}
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    volumes:
      - ./www:/srv/www
    working_dir: /srv/www

  php:
    build:
      args:
        - PHP_VERSION
        - COMPOSER_VERSION
        - MAILPIT_VERSION
        - USER_ID
        - GROUP_ID
        - SITE_TYPE
      context: ./docker/php
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-php
    depends_on:
      - mailpit
      - memcached
      - mysql
      - redis
    environment:
      - COMPOSER_HOME=/.config/composer
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    volumes:
      - ./www:/srv/www
      - ./logs/php:/var/log/php
    working_dir: /srv/www

  redis:
    command: [
      'redis-server',
      '--appendonly',
      'yes',
    ]
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-redis
    image: redis:${REDIS_VERSION:-7.0-alpine}
    volumes:
      - redisdata:/data

volumes:
  mailpitdata:
  mysqldata:
  redisdata:
