services:
  mailpit:
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-mailpit
    image: axllent/mailpit:v${MAILPIT_VERSION:-1.22.3}
    ports:
      - ${MAILPIT_WEB_PORT:-8025}:8025
      - ${MAILPIT_SMTP_PORT:-1025}:1025
    networks:
      - backend
    profiles:
      - dev
    restart: unless-stopped
    volumes:
      - mailpitdata:/data

  memcached:
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-memcached
    healthcheck:
      test: ["CMD-SHELL", "echo stats | nc localhost 11211 | grep pid"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: memcached:${MEMCACHED_VERSION:-1.6-alpine}
    networks:
      - backend
    restart: unless-stopped

  mysql:
    command: [
      '--character-set-server=${MYSQL_ENCODING:-utf8mb4}',
      '--collation-server=${MYSQL_COLLATION:-utf8mb4_unicode_ci}'
    ]
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-mysql
    stop_grace_period: 30s
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-docker}
      - MYSQL_USER=${MYSQL_USER:-docker}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: mysql:${MYSQL_VERSION:-8.4}
    networks:
      - backend
    restart: unless-stopped
    ports:
      - ${BIND_ADDRESS:-0.0.0.0}:${MYSQL_PORT:-3306}:3306
    volumes:
      - mysqldata:/var/lib/mysql

  nginx:
    build:
      args:
        - NGINX_VERSION
        - SITE_URL
      context: ./docker/nginx
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-nginx
    restart: unless-stopped
    stop_grace_period: 10s
    depends_on:
      php:
        condition: service_healthy
    ports:
      - ${BIND_ADDRESS:-0.0.0.0}:${NGINX_PORT_UNSECURE:-80}:80
      - ${BIND_ADDRESS:-0.0.0.0}:${NGINX_PORT_SECURE:-443}:443
    networks:
      - frontend
    volumes:
      - ./www:/srv/www
      - ./logs/nginx:/var/log/nginx
    working_dir: /srv/www

  nodejs:
    build:
      args:
        - NODEJS_VERSION
        - USER_ID
        - GROUP_ID
      context: ./docker/nodejs
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-nodejs
    environment:
      - NPM_CONFIG_CACHE=/.config/npm
    image: node:${NODEJS_VERSION:-22.14-alpine}
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    volumes:
      - ./www:/srv/www
      - ./docker/nginx/certs:/srv/docker/nginx/certs
    working_dir: /srv/www

  php:
    build:
      args:
        - PHP_VERSION
        - COMPOSER_VERSION
        - MAILPIT_VERSION
        - USER_ID
        - GROUP_ID
      context: ./docker/php
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-php
    stop_grace_period: 35s
    healthcheck:
      test: ["CMD-SHELL", "SCRIPT_NAME=/ping SCRIPT_FILENAME=/ping REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000 | grep pong"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      memcached:
        condition: service_healthy
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - COMPOSER_HOME=/.config/composer
    networks:
      - frontend
      - backend
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    volumes:
      - ./www:/srv/www
      - ./logs/php:/var/log/php
    working_dir: /srv/www

  horizon:
    build:
      context: ./docker/php
      args:
        - PHP_VERSION
        - COMPOSER_VERSION
        - MAILPIT_VERSION
        - USER_ID
        - GROUP_ID
    command: php /srv/www/artisan horizon
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-horizon
    restart: unless-stopped
    stop_grace_period: 10s
    depends_on:
      php:
        condition: service_healthy
    networks:
      - backend
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    volumes:
      - ./www:/srv/www
      - ./logs/php:/var/log/php
    working_dir: /srv/www

  scheduler:
    build:
      context: ./docker/php
      args:
        - PHP_VERSION
        - COMPOSER_VERSION
        - MAILPIT_VERSION
        - USER_ID
        - GROUP_ID
    command: sh -c 'while true; do php /srv/www/artisan schedule:run --no-interaction; sleep 60; done'
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-scheduler
    restart: unless-stopped
    depends_on:
      php:
        condition: service_healthy
    networks:
      - backend
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    volumes:
      - ./www:/srv/www
      - ./logs/php:/var/log/php
    working_dir: /srv/www

  redis:
    command: [
      'redis-server',
      '--appendonly',
      'yes',
    ]
    container_name: ${COMPOSE_PROJECT_NAME:-docker-lemp}-redis
    stop_grace_period: 10s
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: redis:${REDIS_VERSION:-7.0-alpine}
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - redisdata:/data

networks:
  frontend:
  backend:

volumes:
  mailpitdata:
  mysqldata:
  redisdata:
