server {
    listen [::]:80;
    listen 80;

    server_name www.{{SITE_URL}} {{SITE_URL}};

    return 301 https://{{SITE_URL}}$request_uri;
}

server {
    listen [::]:443 ssl;
    listen 443 ssl;

    http2 on;

    server_name www.{{SITE_URL}};

    include h5bp/tls/ssl_engine.conf;
    include h5bp/tls/certificate_files.conf;
    include h5bp/tls/policy_balanced.conf;

    return 301 $scheme://{{SITE_URL}}$request_uri;
}

server {
    listen [::]:443 ssl;
    listen 443 ssl;

    http2 on;

    # The host name to respond to
    server_name {{SITE_URL}};

    include h5bp/tls/ssl_engine.conf;
    include h5bp/tls/certificate_files.conf;
    include h5bp/tls/policy_balanced.conf;

    # Path for static files
    root {{DOCUMENT_ROOT}};

    index index.php index.html;

    # Custom error pages
    include h5bp/errors/custom_errors.conf;

    # PHP
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_buffers 8 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Include the basic h5bp config set
    include h5bp/security/referrer-policy.conf;
    include h5bp/security/x-content-type-options.conf;
    include h5bp/security/x-frame-options.conf;
    include h5bp/location/security_file_access.conf;
    include h5bp/cross-origin/requests.conf;
}
